#
# ThingsBoard, Inc. ("COMPANY") CONFIDENTIAL
#
# Copyright © 2016-2024 ThingsBoard, Inc. All Rights Reserved.
#
# NOTICE: All information contained herein is, and remains
# the property of ThingsBoard, Inc. and its suppliers,
# if any.  The intellectual and technical concepts contained
# herein are proprietary to ThingsBoard, Inc.
# and its suppliers and may be covered by U.S. and Foreign Patents,
# patents in process, and are protected by trade secret or copyright law.
#
# Dissemination of this information or reproduction of this material is strictly forbidden
# unless prior written permission is obtained from COMPANY.
#
# Access to the source code contained herein is hereby forbidden to anyone except current COMPANY employees,
# managers or contractors who have executed Confidentiality and Non-disclosure agreements
# explicitly covering such access.
#
# The copyright notice above does not evidence any actual or intended publication
# or disclosure  of  this source code, which includes
# information that is confidential and/or proprietary, and is a trade secret, of  COMPANY.
# ANY REPRODUCTION, MODIFICATION, DISTRIBUTION, PUBLIC  PERFORMANCE,
# OR PUBLIC DISPLAY OF OR THROUGH USE  OF THIS  SOURCE CODE  WITHOUT
# THE EXPRESS WRITTEN CONSENT OF COMPANY IS STRICTLY PROHIBITED,
# AND IN VIOLATION OF APPLICABLE LAWS AND INTERNATIONAL TREATIES.
# THE RECEIPT OR POSSESSION OF THIS SOURCE CODE AND/OR RELATED INFORMATION
# DOES NOT CONVEY OR IMPLY ANY RIGHTS TO REPRODUCE, DISCLOSE OR DISTRIBUTE ITS CONTENTS,
# OR TO MANUFACTURE, USE, OR SELL ANYTHING THAT IT  MAY DESCRIBE, IN WHOLE OR IN PART.
#

version: '3.0'

services:
  postgres:
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
  tb-monolith:
    volumes:
      - tb-log-volume:/var/log/thingsboard
  tb-edge:
    volumes:
      - tb-edge-log-volume:/var/log/tb-edge
      - tb-edge-data-volume:/data
  tb-edge-kafka:
    volumes:
      - tb-edge-log-volume-kafka:/var/log/tb-edge
      - tb-edge-data-volume-kafka:/data
  tb-edge-38:
    volumes:
      - tb-edge-log-volume-38:/var/log/tb-edge
      - tb-edge-data-volume-38:/data
  tb-edge-37:
    volumes:
      - tb-edge-log-volume-37:/var/log/tb-edge
      - tb-edge-data-volume-37:/data
volumes:
  postgres-db-volume:
    external:
      name: ${POSTGRES_DATA_VOLUME}
  tb-log-volume:
    external:
      name: ${TB_LOG_VOLUME}
  tb-edge-log-volume:
    external:
      name: ${TB_EDGE_LOG_VOLUME}
  tb-edge-data-volume:
    external:
      name: ${TB_EDGE_DATA_VOLUME}
  tb-edge-log-volume-kafka:
    external:
      name: ${TB_EDGE_LOG_VOLUME_KAFKA}
  tb-edge-data-volume-kafka:
    external:
      name: ${TB_EDGE_DATA_VOLUME_KAFKA}
  tb-edge-log-volume-38:
    external:
      name: ${TB_EDGE_LOG_VOLUME_38}
  tb-edge-data-volume-38:
    external:
      name: ${TB_EDGE_DATA_VOLUME_38}
  tb-edge-log-volume-37:
    external:
      name: ${TB_EDGE_LOG_VOLUME_37}
  tb-edge-data-volume-37:
    external:
      name: ${TB_EDGE_DATA_VOLUME_37}
